# Generated by Django 6.0 on 2026-01-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='filter_key',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
