# Generated by Django 6.0 on 2026-01-12 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('razorpay', 'Razorpay')], default='cod', max_length=20),
        ),
    ]
